import java.util.EventListener;
/**
 * The AddCustomersPanelListener interface defines a contract for classes that want to listen to
 * events generated by the AddCustomersPanel in the Aquapark Management application.
 */
public interface AddCustomersPanelListener extends EventListener {
    /**
     * Invoked when an AddCustomersPanelEvent occurs.
     *
     * @param acpe The AddCustomersPanelEvent that occurred.
     */
    void addCustomersPanelEventOccurred(AddCustomersPanelEvent acpe);

}
